services:
  mqtt_dumper_base: &mqtt_dumper_base
    image: forumviriumhelsinki/containers-mqtt-dumper
    build:
      context: .
    profiles:
      - "donotstart"
    volumes:
      - ../../data/raw:/app/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  hsl_dumper_2015:
    <<: *mqtt_dumper_base
    container_name: hsl_dumper_2015
    volumes:
      - ../../data/raw/2015:/app/data
    environment:
      TOPICS: "/hfp/v2/journey/ongoing/+/tram/+/+/2015/#"

  hsl_dumper_koskelantie_50:
    <<: *mqtt_dumper_base
    container_name: hsl_dumper_koskelantie_50
    volumes:
      - ../../data/raw/koskelantie_50:/app/data
    environment:
      TOPICS: "/hfp/v2/journey/ongoing/+/bus/+/+/1057/+/+/+/+/+/60;24/29/15/#"

  hsl_dumper_65_71_79:
    <<: *mqtt_dumper_base
    container_name: hsl_dumper_65_71_79
    volumes:
      - ../../data/raw/65_71_79:/app/data
    environment:
      TOPICS: '"/hfp/v2/journey/ongoing/+/bus/+/+/1071/#" "/hfp/v2/journey/ongoing/+/bus/+/+/1065/#" "/hfp/v2/journey/ongoing/+/bus/+/+/1079/#"'

  hsl_dumper_all:
    <<: *mqtt_dumper_base
    container_name: hsl_dumper_all
    volumes:
      - ../../data/raw/all:/app/data
    environment:
      TOPICS: "/hfp/v2/journey/ongoing/#"

  # Example of additional dumper instance with different topics
  # mqtt_dumper_2:
  #   extends: mqtt_dumper
  #   environment:
  #     - MQTT_TOPICS=${MQTT_TOPICS_2}
  #   command: python mqtt_dumper.py --output-dir /app/data --topics ${MQTT_TOPICS_2}
