services:
  mqtt_dumper:
    build:
      context: ../..
      dockerfile: docker/mqtt_dumper/Dockerfile
    volumes:
      - ../../data/raw:/app/data
    environment:
      - MQTT_TOPICS=${MQTT_TOPICS}
      - MQTT_USERNAME=${MQTT_USERNAME:-}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-}
    command: python hfp_mqtt_data_dumper.py --output-dir /app/data --topics ${MQTT_TOPICS}
    restart: unless-stopped
  # Example of additional dumper instance with different topics
  # mqtt_dumper_2:
  #   extends: mqtt_dumper
  #   environment:
  #     - MQTT_TOPICS=${MQTT_TOPICS_2}
  #   command: python mqtt_dumper.py --output-dir /app/data --topics ${MQTT_TOPICS_2}
